# backend/render.yaml
services:
  - type: web
    name: sales-analyser-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false


        # $env:GEMINI_API_KEY="AIzaSyDCmBnDYy_QJub9zjVItr9ARCPOINhJP4w"
        # uvicorn main:app --reload --port 8000